export = {
    "{": "L_BRACE",
    "}": "R_BRACE",
    "=": "IGUAL",
    "<": "L_EXPRESSION",
    ">": "R_EXPRESSION",
    "(": "L_EXPRESSION",
    ")": "R_EXPRESSION",
    "+": "MAS",
    "-": "MENOS",
    "*": "POR",
    "/": "ENTRE",
    "**": "EXP",
    "%": "RESTO",
    "?": "MAYOR",
    "¿": "MENOR",
    ">=": "MAYOR_IGUAL",
    "<=": "MENOR_IGUAL",
    "!": "NO",
    "==": "IGUAL_TIPADO",
    ";": "SEPARACION"
};